name: Run Pyre

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Create virtual environment
      run: |
        python -m venv venv
    - name: Install Pyre requirements
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Pyre
      run: |
        source venv/bin/activate
        pyre check
